### PR TITLE
v1.0.0

### LINKED ISSUE #2: API Documentation is 404
Hi, the link in the readme is incorrect.
https://swiftpackageindex.com/exPHAT/SwiftBluetooth/1.0.0/documentation/

Should be:

https://swiftpackageindex.com/exPHAT/SwiftBluetooth/0.1.0/documentation/

### LINKED ISSUE #4: Include advertisement data and RSSI for discovered peripherals
You are currently ignoring the values here: https://github.com/exPHAT/SwiftBluetooth/blob/69af89de1c25d96481a75e863d728cc3850e5daf/Sources/SwiftBluetooth/CentralManager/CentralManager%2Basync.swift#L35

But those values are useful. For example, the RSSI provided there is the only way to get the RSSI without connecting to a peripheral first.

Maybe add a `initialRSSI` and `advertisementData` property to `Peripheral`.

Would be nice if `advertisementData ` was a struct based on fetching these keys from the original advertisement data: https://developer.apple.com/documentation/corebluetooth/cbcentralmanagerdelegate/advertisement_data_retrieval_keys

On a sidenote: I think the RSSI should be returned as a Double, not NSNumber.

### LINKED ISSUE #5: `waitUntilReady` waits forever when there's no Bluetooth authorization
This may very well be the correct behavior, but I think at least it should be documented.

### LINKED ISSUE #6: Central#connect should respect cancellation
Something like this:

```swift
@available(iOS 13, macOS 10.15, watchOS 6.0, tvOS 13.0, *)
@discardableResult
func connect(_ peripheral: Peripheral, options: [String: Any]? = nil) async throws -> Peripheral {
	try await withTaskCancellationHandler {
		try await withCheckedThrowingContinuation { cont in
			self.connect(peripheral, options: options) { result in
				switch result {
				case .success(let peripheral):
					cont.resume(returning: peripheral)
				case .failure(let error):
					cont.resume(throwing: error)
				}
			}
		}
	} onCancel: {
		cancelPeripheralConnection(peripheral)
	}
}
```

### LINKED ISSUE #7: `.connect()` and `.scanForPeripherals()` should have a timeout duration parameter
For example, if you try to use `.connect()` with a device that is offline, it will await forever.

### PR DESCRIPTION
**Pull request by exPHAT**
Close #2
Close #4
Close #5 
Close #6 
Close #7

### CODE REVIEW

File: Sources/SwiftBluetooth/CentralManager/CentralManager+async.swift [hunk 1]
```diff
@@ -3,33 +3,50 @@ import CoreBluetooth
...
-                    cont.resume(returning: peripheral)
-                case .failure(let error):
-                    cont.resume(throwing: error)
+    func connect(_ peripheral: Peripheral, timeout: TimeInterval, options: [String: Any]? = nil) async throws -> Peripheral {
+        var cancelled = false
+        var continuation: CheckedContinuation<Peripheral, Error>?
+        let cancel = {
+            cancelled = true
+            self.cancelPeripheralConnection(peripheral)
+            continuation?.resume(throwing: CentralError.cancelled)
```
Comment (sindresorhus) [inline Sources/SwiftBluetooth/CentralManager/CentralManager+async.swift:22]: It may be better to throw a `CancellationError`: https://developer.apple.com/documentation/swift/cancellationerror

File: Sources/SwiftBluetooth/Peripheral/Peripheral+DiscoveryInfo.swift [hunk 2]
```diff
@@ -0,0 +1,58 @@
+import Foundation
+import CoreBluetooth
+
+extension Peripheral {
+    public struct DiscoveryInfo {
+        public var RSSI: Int
```
Comment (sindresorhus) [inline Sources/SwiftBluetooth/Peripheral/Peripheral+DiscoveryInfo.swift:6]: The convention is to use lowercase, even for acronyms: https://developer.apple.com/documentation/corelocation/clbeacon/1621557-rssi#

File: Sources/SwiftBluetooth/Peripheral/Peripheral+DiscoveryInfo.swift [hunk 3]
```diff
@@ -0,0 +1,58 @@
...
+
+            public var localName: String? {
+                data[CBAdvertisementDataLocalNameKey] as? String
+            }
+
+            public var manufacturerData: Data? {
+                data[CBAdvertisementDataManufacturerDataKey] as? Data
+            }
+
+            public var serviceData: [CBUUID : Data]? {
```
Comment (sindresorhus) [inline Sources/SwiftBluetooth/Peripheral/Peripheral+DiscoveryInfo.swift:29]: Optional dictionaries and arrays are generally an anti-pattern in Swift. It's better to just use an empty dictionary instead of `nil`.

File: Sources/SwiftBluetooth/Peripheral/Peripheral+DiscoveryInfo.swift [hunk 4]
```diff
@@ -0,0 +1,58 @@
...
+                data[CBAdvertisementDataServiceDataKey] as? [CBUUID : Data]
```
Comment (sindresorhus) [inline Sources/SwiftBluetooth/Peripheral/Peripheral+DiscoveryInfo.swift:30]:
```suggestion
                data[CBAdvertisementDataServiceDataKey] as? [CBUUID : Data] ?? [:]
```

**Review by sindresorhus — CHANGES_REQUESTED** [review]

File: Sources/SwiftBluetooth/Peripheral/Peripheral+DiscoveryInfo.swift (hunk 2 above)
Comment (exPHAT) [reply Sources/SwiftBluetooth/Peripheral/Peripheral+DiscoveryInfo.swift:6]: I was following the arguments used in [central manager delegate](https://developer.apple.com/documentation/corebluetooth/cbcentralmanagerdelegate/1518937-centralmanager) and [peripheral delegate](https://developer.apple.com/documentation/corebluetooth/cbperipheraldelegate/1620304-peripheral).

Glad they've set the precedent of using lowercase somewhere else, I honestly assumed it was some convention with RSSI specifically.

File: Sources/SwiftBluetooth/Peripheral/Peripheral+DiscoveryInfo.swift (hunk 3 above)
Comment (exPHAT) [reply Sources/SwiftBluetooth/Peripheral/Peripheral+DiscoveryInfo.swift:29]: Determining if the key was advertised at all might be of use to some people. Though for ease-of-use I probably agree that adding a default here is much more convenient.

I guess they can always index on the underlying CoreBluetooth dictionary to determine that though. Will implement (for the arrays too).

**Comment by mgibbs189** [comment]
@exPHAT @sindresorhus Thanks for your work on this project. It makes BLE so much easier to work with.

Any chance you could merge in this PR?

**Comment by exPHAT** [comment]
@mgibbs189 Merged!

**Comment by mgibbs189** [comment]
@exPHAT That was quick, thank you!

Out of curiousity, are you available for contract work? I have a small app that could use a review / sanity check 😄

**Comment by exPHAT** [comment]
@mgibbs189 Shoot me an email with some info about your project, aaron@(github username).com
